### ISSUE TITLE
data about entity_pos.pkl and input_ids.h5

### ISSUE THREAD

**Issue by zhuoChan97** [thunlp/PELT#2]
how can we get this data ,or give us a example of this data if it is convenient.

**Comment by tom68-ll** [comment]
I have the same question，Could you please improve the documentation?

**Comment by zhuoChan97** [comment]
and  ,in the RE/run_wiki_80, start with CUDA_VISIBLE_DEVICES=0 python3 run_re_bracket.py .where is the re_bracket.py
hope u can improve this ,

**Comment by YeDeming** [comment]
Sorry for the late response. We have updated the link to the dataset and preprocessing code.
