### ISSUE TITLE
Bugs in FewRel 

### ISSUE THREAD

**Issue by LinhanZ** [thunlp/PELT#3]
Hi,
I found there are some bugs in FewRel/fewshot_re_kit/data_loader.py.
In line 59-66: 1. The tokenize returns 4 values including a value for mask. Besides, the type for  h_pos and t_pos is int not list. Hence, 63-66 could not simply add a number. 
Could you please help me deal with issue?

Thanks

**Comment by YeDeming** [comment]
Hi,
`self.encoder.tokenize` refers to 

https://github.com/thunlp/PELT/blob/9a9177a8c5de39cc21ad68315fdaa45160f837ea/FewRel/fewshot_re_kit/sentence_encoder.py#L168-L240

or 


https://github.com/thunlp/PELT/blob/9a9177a8c5de39cc21ad68315fdaa45160f837ea/FewRel/fewshot_re_kit/sentence_encoder.py#L245-L339


h_pos is a tuple of (left marker's postiion,  right marker's position).   We use RoBERTa-based encoder  in the paper. And I note that there is a bug in  BERTSentenceEncoder and try to fix it soon.

**Comment by YeDeming** [comment]
Code is updated.
