### ISSUE TITLE
Inqury about KEPLER implementation

### ISSUE THREAD

**Issue by Kunlun-Zhu** [thunlp/PELT#4]
Hi, I would like to know if this repo contain the KEPLER implementation for the experiment results in the paper, Thanks a lot.

**Comment by YeDeming** [comment]
The implementation of KEPLER is the same as RoBERTa. This implemention set the argument --model_type roberta

**Comment by Kunlun-Zhu** [comment]
So the KEPLER is implement inside here? [modeling_roberta.py](https://github.com/thunlp/PELT/blob/34195d47a2a765c763208c631c32fef96a075cba/transformers/src/transformers/modeling_roberta.py) To my best understanding, KEPLER is not exactly same as RoBERTa implementation, so I get a bit confused on this.

**Comment by YeDeming** [comment]
In finetuning, KEPLER is the same as RoBERTa. The pretraining code of KEPLER is [here](https://github.com/THU-KEG/KEPLER).

**Comment by Kunlun-Zhu** [comment]
Yeah I see, I was looking for a possible new pretraining code implementation here. Thanks.
