### ISSUE TITLE
Is there a direct code for Pluaggable Entity lookup Table?

### ISSUE THREAD

**Issue by Kunlun-Zhu** [thunlp/PELT#5]
Hi, Deming, thanks for the work.
After reading some of the source code, is there a direct abstract of the Lookup table code, or we just only use the generate embeddings?
If there is one, how may I use it in some other task such as link prediction, thanks.

**Comment by Kunlun-Zhu** [comment]
I see a 'lookup_table' parameter here, [modeling_tf_transfo_xl.py](https://github.com/thunlp/PELT/blob/master/transformers/src/transformers/modeling_tf_transfo_xl.py)  
Is there where the 'pluggable Entity look up table' was represented.

**Comment by Kunlun-Zhu** [comment]
I also see one here [modeling_xlnet.py](https://github.com/thunlp/PELT/blob/34195d47a2a765c763208c631c32fef96a075cba/transformers/src/transformers/modeling_xlnet.py)

**Comment by YeDeming** [comment]
We should re-generate the entity embeddings according to the required qid for other tasks.  The related code is at:
https://github.com/thunlp/PELT/blob/eefecaada2094996cea0c1053cca59307fadbd49/transformers/src/transformers/modeling_robertaent.py#L255-L260

**Comment by Kunlun-Zhu** [comment]
Thanks, I think that I get the idea.
