### ISSUE TITLE
Some question about infuse information to entity embedding.

### ISSUE THREAD

**Issue by BAOOOOOM** [thunlp/PELT#7]
Hello, I have read your paper and your code, I think it is a meanful work which can be used in many field  to improve performance.  I want to cite your method to my work, but I cannot understand how to use enhanced entity embedding in downstream. I have tried to use PLM1 to get context's word embedding, then use new embedding to replace entity's embedding and send it to PLM2. The result is terrible, can  you help me with this question? Thank you very much!

**Comment by YeDeming** [comment]
We generate the embedding from PLM1 and then appy it on PLM1 to extend its vocabulary. Hence the embeding doesn't support PLM2.

**Comment by BAOOOOOM** [comment]
> We generate the embedding from PLM1 and then appy it on PLM1 to extend its vocabulary. Hence the embeding doesn't support PLM2.

Thanks!
